### PR TITLE
Removing javax restriction from packaging

### PR DESCRIPTION
**Pull request by jvanzyl**
... like javax.inject.**

in the context of Maven I don't believe we're ever going to give JarJar direct access to the JRE where
  everything can be pulled in.

  in my case here where i am making a self-contained JSR330-based server removing the javax restricted resulted
  in a working uber jar.

### CODE REVIEW

**Comment by mcculls** [comment]
Sounds reasonable, I just need to double-check why this check was added in the first place...

**Comment by mcculls** [comment]
This rule has been in ever since the keep rule was added - AFAICT the idea is that you don't want to keep packages that ship with the JVM (mainly java, but also covers some javax packages). However there are also javax packages that don't ship with the JVM that you do want to keep.

One question - does the build work if you use the unpatched plugin and add an explicit <keep> rule for javax.inject?

**Comment by jvanzyl** [comment]
Nope.

On Mar 21, 2012, at 10:27 AM, Stuart McCulloch wrote:

> This rule has been in ever since the keep rule was added - AFAICT the idea is that you don't want to keep packages that ship with the JVM (mainly java, but also covers some javax packages). However there are also javax packages that don't ship with the JVM that you do want to keep.
> 
> One question - does the build work if you use the unpatched plugin and add an explicit <keep> rule for javax.inject?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sonatype/jarjar-maven-plugin/pull/1#issuecomment-4618308

Thanks,

Jason

---

Jason van Zyl
Founder,  Apache Maven

## http://twitter.com/jvanzyl

We know what we are, but know not what we may be.

  -- Shakespeare

**Comment by mcculls** [comment]
Merged and built on grid: https://builds.sonatype.org/job/jarjar-maven-plugin/8/

**Comment by mgenov** [comment]
Hello, 

Is this fix still valid ? 

I'm trying to include: <include>javax.inject:javax.inject</include>, and when jar is packaged I get java.lang.NoClassDefFoundError: javax/inject/Provider

**Comment by mcculls** [comment]
This has been fixed in trunk but has not yet been released - if you can confirm the fix works for you (by checking out the jarjar-maven-plugin, building it locally, then updating your project to use that 1.6-SNAPSHOT) then I can stage a release.

**Comment by mgenov** [comment]
Works great.

I think that I found another packaging issue, but I will post it as issue.

**Pull request merged**
