### PR TITLE
Integration tests based on maven-invoker-plugin

### PR DESCRIPTION
**Pull request by jussimalinen**
This pull request includes integration tests based on maven-invoker-plugin, and also a change to mojo execution, that sets directories with files as included in jar: 58bbb1c9836acfb9b48c351f53f6121880fd0471

### CODE REVIEW

**Comment by mcculls** [comment]
Looks good, thanks! I'll add another IT for the leftover entries scenario and fix that without regressing this testcase.

**Comment by jussimalinen** [comment]
Excellent! Thanks!

Do you have any plans/guestimates for the schedule of the next release? (I'm okay with "no idea", just wanted to ask. I think we can use SNAPSHOT to compile our project until then...)

**Comment by mcculls** [comment]
Definitely before the end of the month, hopefully sooner depending on my spare time.

**Comment by mcculls** [comment]
jarjar-maven-plugin 1.7 has been released:

   http://search.maven.org/#artifactdetails%7Corg.sonatype.plugins%7Cjarjar-maven-plugin%7C1.7%7Cmaven-plugin

**Pull request merged**
